<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/9/19 0019
 * Time: 10:49
 */

return array(
    'ERROR_NONE' => 0,
    'ERROR_APPCMD_FAIL' => 227,
    'ERROR_VER_CODE_ERROR' => 228,
    'ERROR_SEC_ERROR' => 229,
    'ERROR_ADDEXISTUSER_SMS_NOTFINISH' => 230,
    'ERROR_DELUSER_LIST_NOT_FOUND' => 231,
    'ERROR_ADDUSER_LIST_FULL' => 232,
    'ERROR_ADDUSER_ROLE_UNAVAILABLE' => 233,
    'ERROR_ADDUSER_VER_SMS_NOTFINISH' => 234,
    'ERROR_SMS_TOOFAST' => 235,
    'ERROR_TOKEN' => 236,
    'ERROR_USER_NOT_REG' => 237,
    'ERROR_SUBSCRIBED_IN_USERLIST' => 238,
    'ERROR_USER_PWD' => 239,
    'ERROR_SMS_CODE_ERR' => 240,
    'ERROR_SMS_CODE_TIMEOUT' => 241,
    'ERROR_VER_SMS_NOTFINISH' => 242,
    'ERROR_VER_SMS_FAILED' => 243,
    'ERROR_USER_EXISTED' => 244,
    'ERROR_USER_SMS_DIDNOTSEND' => 245,
    'ERROR_WAYPOINT_EMPTY' => 246,
    'ERROR_SUBSCRIBED_ALREADY' => 247,
    'ERROR_PERIMITION_ADMIN' => 248,
    'ERROR_ERROR_DEVICE_PWD' => 249,
    'ERROR_UNSUBSCRIBED' => 250,
    'ERROR_PERIMITION' => 251,
    'ERROR_FAILED' => 252,
    'ERROR_PARAM_ERROR' => 253,
    'ERROR_TIME_OUT' => 254,
    'ERROR_DB_ERROR' => 255,
);
