var translate = {
    chanpingzhongxin: ["产品中心", "Products"],
    xinwendongtai: ["新闻动态", "Nation"],
    guanyuwomen: ["关于我们", "AboutUs"],
    zaixianshanchen: ["在线商城", "Shop"],
    youqinglianjie: ["友情链接", "Fk"],
    dierdaizhinengshoubiao: ["第二代智能手表", "Seconches"],
    gongsixinwen: ["公司新闻", "Comws"],
    hanyedongtai: ["行业动态", "Indmics"],
    shipingzhongxin: ["视频中心", "Videnter"],
    guanyutengxuertongshoubiao: ["关于腾讯儿童手表", "Aboutatches"],
    lianxiwomen: ["联系我们", "Contact us"],
    shiyongshuoming: ["使用说明", "Instructions"],
    kefurexian: ["7X24小时客服热线", ""],
    shouye: ["首页", "Home"],
    ertongpingpandiannao: ["腾讯儿童平板电脑", "Tablet PC for children"],
    ertongqqjing: ["腾讯儿童qq镜", "Children's QQ lens"],
    ertongyanbaobiao: ["腾讯儿童眼保膘", "China children's eyes"],
    appxiazai: ["APP下载", "Download"],
    gujianshengji: ["固件升级", "FirmwareUpdate"],
    tengjiakejiyouxiangongsi: ["深圳腾家科技有限公司", "Company TengJiaKeJi"],
    gongsijianjie: ["公司简介", "Company profile"],
    xinwenzhongxin: ["新闻中心", "News"],
    gongsigongzuori: ["公司工作日", "Company working day"],
    banquansuoyou: ["版权所有", "Copyright"],
    zhutuichanpin: ["主推产品", "Main push products"],
    tengxunertongshoubiaoxilie: ["腾讯儿童手表系列", "Main push products"],
    apple1212: ["苹果1212", "apple"]
};