<?php
//flag
define("DEBUG",true);
//dir
define("VIEW_DIR",ROOT_DIR."app/view/");
define("CTRL_DIR",ROOT_DIR."app/controller/");
define("MODEL_DIR",ROOT_DIR."app/model/");
define("EXTENSION_DIR",ROOT_DIR."extensions/");
//string
define("BR","<br>");
//session
define("COOKIE_SESSION_KEY","sessionId");
define("COOKIE_SESSION_EXT",3600);